import React from 'react';

interface LegalModalProps {
  isOpen: boolean;
  onClose: () => void;
}

const SectionTitle: React.FC<{ children: React.ReactNode }> = ({ children }) => (
    <h2 className="text-2xl font-bold text-gray-900 dark:text-white mt-6 mb-3">{children}</h2>
);

const SubTitle: React.FC<{ children: React.ReactNode }> = ({ children }) => (
    <h3 className="text-xl font-semibold text-gray-800 dark:text-gray-200 mt-4 mb-2">{children}</h3>
);

const ListItem: React.FC<{ children: React.ReactNode }> = ({ children }) => (
    <li className="mb-2 ml-4 list-disc">{children}</li>
);

export const LegalModal: React.FC<LegalModalProps> = ({ isOpen, onClose }) => {
  if (!isOpen) {
    return null;
  }

  return (
    <div className="fixed inset-0 bg-black bg-opacity-50 z-50 flex items-center justify-center p-4" role="dialog" aria-modal="true">
      <div className="bg-white dark:bg-slate-800 rounded-lg shadow-xl w-full max-w-3xl max-h-[90vh] flex flex-col">
        <div className="flex justify-between items-center p-4 border-b border-gray-200 dark:border-slate-700 sticky top-0 bg-white dark:bg-slate-800">
          <h1 className="text-xl font-bold text-gray-900 dark:text-white">Legal Information</h1>
          <button onClick={onClose} className="text-gray-500 hover:text-gray-800 dark:text-gray-400 dark:hover:text-white" aria-label="Close">
            <svg className="w-6 h-6" fill="none" stroke="currentColor" viewBox="0 0 24 24"><path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M6 18L18 6M6 6l12 12" /></svg>
          </button>
        </div>
        <div className="p-6 overflow-y-auto text-gray-700 dark:text-gray-300 text-sm">
          <p className="mb-4">Last Updated: {new Date().toLocaleDateString()}</p>

          {/* Terms of Service */}
          <SectionTitle>Terms of Service</SectionTitle>
          <p>By using SareeStage ("Service"), you agree to these terms. Please read them carefully.</p>
          <SubTitle>1. Service Description</SubTitle>
          <p>The Service provides a virtual try-on experience for sarees using artificial intelligence. Users upload their photo and images of a saree to generate a new image.</p>
          <SubTitle>2. User-Uploaded Content</SubTitle>
          <p>You are solely responsible for the images you upload. You must have the rights to use and upload these images. Do not upload content that is illegal, offensive, or infringes on others' rights.</p>
          <SubTitle>3. Prohibited Use</SubTitle>
          <p>You may not use the Service to create harmful, pornographic, or misleading content. We reserve the right to block users who violate these terms.</p>
          <SubTitle>4. Disclaimers</SubTitle>
          <p>The Service is provided "as is". AI-generated images may contain inaccuracies or artifacts. We are not responsible for the quality or accuracy of the generated images.</p>

          {/* Privacy Policy */}
          <SectionTitle>Privacy Policy</SectionTitle>
          <p>Your privacy is critically important to us. This policy outlines how we handle your data.</p>
          <SubTitle>1. No Image Storage - Our Core Promise</SubTitle>
          <p className="font-bold bg-yellow-100 dark:bg-yellow-900/50 p-3 rounded-md">
            We do not store, save, or collect any images you upload or that are generated by the service on our servers. All uploaded and generated images are processed in-memory for the sole purpose of generating your virtual try-on and are permanently discarded when you close the browser tab, start over, or end your session.
          </p>
          <SubTitle>2. Data Processing</SubTitle>
          <p>To generate the try-on image, your uploaded photos are sent securely to the Google Gemini API for processing. The images are used only for the generation task and are subject to Google's AI/ML data usage policies. We do not permit Google or any third party to use your images for any other purpose.</p>
          <SubTitle>3. Cookies and Analytics</SubTitle>
          <p>We do not use tracking cookies. We may use anonymous, aggregate analytics to understand service usage and improve the application, but this data is not tied to any personal information.</p>
          
          {/* GDPR Compliance */}
          <SectionTitle>GDPR Compliance</SectionTitle>
          <p>We are committed to compliance with the General Data Protection Regulation (GDPR).</p>
          <SubTitle>1. Data Controller and Processor</SubTitle>
          <p>You are the Data Controller of the images you upload. SareeStage acts as a Data Processor, handling the images on your behalf for the specific task you requested.</p>
          <SubTitle>2. Your Rights</SubTitle>
          <p>Under GDPR, you have rights regarding your personal data. Our service architecture respects these rights by design:</p>
          <ul>
            <ListItem><strong>Right to Access & Rectification:</strong> Since we do not store your images, you maintain control. You can access or change your images by re-uploading them on your device.</ListItem>
            <ListItem><strong>Right to Erasure ('Right to be Forgotten'):</strong> This is fulfilled automatically. All image data is erased from memory as soon as your session ends. There is nothing for us to delete because we don't store it.</ListItem>
            <ListItem><strong>Data Portability:</strong> You can download the generated image at any time before your session ends.</ListItem>
          </ul>
          <SubTitle>3. Data Transfer</SubTitle>
          <p>Your images are processed via the Google Gemini API, which may involve data transfer to servers in different regions. All transfers are conducted securely.</p>
        </div>
        <div className="p-4 border-t border-gray-200 dark:border-slate-700 sticky bottom-0 bg-white dark:bg-slate-800">
            <button
                onClick={onClose}
                className="w-full bg-fuchsia-600 hover:bg-fuchsia-700 text-white font-bold py-2 px-4 rounded-lg"
            >
                Close
            </button>
        </div>
      </div>
    </div>
  );
};